name: Daily App Update

on:
  schedule:
    # This runs at midnight EST (5 AM UTC)
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Trigger app update
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          # Start the app with logging
          python app.py > app.log 2>&1 &
          
          # Store the PID
          APP_PID=$!
          
          # Wait longer for the app to start
          echo "Waiting for app to start..."
          sleep 30
          
          # Check if the process is still running
          if ps -p $APP_PID > /dev/null; then
            echo "App is running, attempting to connect..."
            curl -v http://localhost:7860
          else
            echo "App failed to start. Here's the log:"
            cat app.log
            exit 1
          fi
          
          # Kill the app
          kill $APP_PID || true

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update content $(date)" && git push)

      - name: Update Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          # Create or update the space
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_folder(
              folder_path='.',
              repo_id='wak1616/wifeapp',
              repo_type='space',
              token='$HF_TOKEN'
          )
          "
